#!/bin/bash

TOOL_DIR=".tech"

if [ -d "${TOOL_DIR}" ]; then
  rm -rf "${TOOL_DIR}"
fi

mkdir -p "${TOOL_DIR}"
cd "${TOOL_DIR}" || exit

git init --quiet
git remote add origin https://github.com/arnia/magento-tech.git
git fetch origin --quiet
git checkout origin/master --quiet
rm -rf .git .gitignore online
