#!/bin/bash

mkdir -p .tech
cd .tech
git init --quiet
git remote add origin https://github.com/arnia/magento-tech.git
git fetch origin --quiet
git checkout origin/master --quiet
rm -rf .git .gitignore online